- name: Apply macOS defaults
  hosts: localhost
  tasks: 
    - name: Sync defaults
      command: "defaults import {{ item }} files/defaults/{{ item }}.plist"
      with_items:
        - com.apple.AppleMultitouchTrackpad
        - com.apple.finder
        - NSGlobalDomain
        - com.apple.dock
