- name: "Install homebrew formulae"
  hosts: localhost
  vars:
    taps:
      - homebrew/cask
    casks:
      - quicklook-json
      - qlmarkdown
      - docker
      - bartender
      - iterm2
      - caffeine
      - flux
      # for some reason, this works better than java cask
      - java-jdk-javadoc
    formulae:
      - python3
      - autoconf
      - automake
      - git
      - hub
      - jq
      - tig
      - ruby
      - rbenv
      - pipenv
      - pyenv-virtualenvwrapper
      - pyenv
      - node
      - nodenv
      - jenv
      - clojure
      - leiningen
    formulae_with_opts:
      - name: macvim
        opts:
          - with-override-system-vim
      - name: universal-ctags/universal-ctags/universal-ctags
        opts:
          - HEAD
          - force
  tasks:
    - name: "Tap the taps"
      homebrew_tap:
        name: "{{ taps }}"
        state: present

    # some formaula require casks (java -> clojure)
    - name: "Install casks"
      homebrew_cask:
        name: "{{ casks }}"
        state: present
        accept_external_apps: True

    - name: "Install formula"
      homebrew:
        name: "{{ formulae }}"
        state: present

    - name: "Install formula with options"
      homebrew:
        name: "{{ item.name }}"
        state: present
        install_options: "{{ item.opts }}"
      with_items: "{{ formulae_with_opts }}"

    - name: Set globals
      shell: "{{ item.exec }} install {{ item.version }} && {{ item.exec }} global {{ item.version }}"
      with_items:
        - exec: nodenv
          version: 8.9.4
        - exec: rbenv
          version: 2.4.4
        - exec: pyenv
          version: 2.7.10
