- name: "Install homebrew formulae"
  hosts: localhost
  vars:
    taps:
      - homebrew/cask
      - caskroom/fonts
    casks:
      - quicklook-json
      - qlmarkdown
      - docker
      - bartender
      - iterm2
      - caffeine
      - flux
      - java
      - intellij-idea-ce
      - visual-studo-code
      - font-source-code-pro
      - font-source-code-pro-for-powerline
    formulae:
      - python3
      - autoconf
      - automake
      - git
      - hub
      - jq
      - tig
      - ruby
      - rbenv
      - pipenv
      - pyenv
      - node
      - nodenv
      - jenv
      - clojure
      - leiningen
      - stack
      - rustup-init
      - go
    formulae_with_opts:
      - name: macvim
        opts:
          - with-override-system-vim
      # this failed to install at one point, had to `brew prune` for it to work
      - name: universal-ctags/universal-ctags/universal-ctags
        opts:
          - HEAD
  tasks:
    - name: "Tap the taps"
      homebrew_tap:
        name: "{{ taps }}"
        state: present

    # some formaula require casks (java -> clojure)
    - name: "Install casks"
      homebrew_cask:
        name: "{{ casks }}"
        state: present
        accept_external_apps: True

    - name: "Install formula"
      homebrew:
        name: "{{ formulae }}"
        state: present

    - name: "Install formula with options"
      homebrew:
        name: "{{ item.name }}"
        state: present
        install_options: "{{ item.opts }}"
      with_items: "{{ formulae_with_opts }}"

    - name: Set globals
      ignore_errors: True
      shell: "{{ item.exec }} install {{ item.version }} && {{ item.exec }} global {{ item.version }}"
      with_items:
        - exec: nodenv
          version: 8.9.4
        - exec: rbenv
          version: 2.4.4
        - exec: pyenv
          version: 2.7.10

    - name: Install rust
      command: 'rustup-init -y'

    - name: Install gvm
      shell: 'zsh < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)'
