- name: "Install homebrew formulae"
  hosts: localhost
  vars:
    taps:
      - homebrew/cask
    casks:
      - quicklook-json
      - qlmarkdown
      - docker
      - bartender
      - iterm2
      - caffeine
      - flux
    formulae:
      - python3
      - autoconf
      - automake
      - universal-ctags/universal-ctags/universal-ctags
      - git
      - hub
      - jq
      - tig
      - ruby
      - rbenv
      - pipenv
      - pyenv
      - nodenv
      - clojure
      - leiningen
    formulae_with_opts:
      - name: macvim
        opts:
          - with-override-system-vim
  tasks:
    - name: "Tap the taps"
      homebrew_tap:
        name: "{{ taps }}"
        state: present

    - name: "Install formula"
      homebrew:
        name: "{{ formulae }}"
        state: present

    - name: "Install formula with options"
      homebrew:
        name: "{{ item.name }}"
        state: present
        install_options: "{{ item.opts }}"
      with_items: "{{ formulae_with_opts }}"

    - name: "Install casks"
      homebrew_cask:
        name: "{{ casks }}"
        state: present
        accept_external_apps: True 
