- name: "Set up shell"
  hosts: localhost
  vars:
    force_dotfiles: False
  tasks:
    - name: Link envd directory
      file:
        path: "~/.env.d"
        src: "{{ playbook_dir }}/files/env.d"
        state: link

    - name: Install zsh
      homebrew:
        name: zsh
        state: present

    - name: Oh-My-Zsh
      shell: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"'

    # NOTE: not linking .gitconfig since it often contains local info (e.g. user email)
    # see gitconfig.yml for universal settings
    - name: List dotfiles
      tags: dotfiles
      register: find_dotfiles
      find:
        paths: files/dotfiles
        hidden: yes
        excludes: '*.sw*'

    - assert:
        that: find_dotfiles.matched > 0

    - name: Link dotfiles
      tags: dotfiles
      file:
        src: "{{ playbook_dir }}/{{ item }}"
        path: "~/{{ item | basename }}"
        state: link
        force: "{{ force_dotfiles }}"
      with_items: "{{ find_dotfiles.files | map(attribute='path') | list }}"