- name: "Set up shell"
  hosts: localhost
  vars:
    force_dotfiles: False
  tasks:
    - name: Link envd directory
      file:
        path: "~/.env.d"
        src: "{{ playbook_dir }}/files/env.d"
        state: link

    - name: Install zsh
      homebrew:
        name: zsh
        state: present

    - name: Oh-My-Zsh
      shell: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"'

    - name: Link dotfiles
      tags: dotfiles
      file:
        src: "{{ playbook_dir }}/files/dotfiles/{{ item }}"
        path: "~/{{ item }}"
        state: link
        force: "{{ force_dotfiles }}"
      with_items:
        - .gitignore
        - .vimrc
        - .zshrc
        - .vim